
spring.application.name=INDIA-SERVICE
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_data
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

info.app.name=Indianservice
info.app.version=1.0

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always