# APPLICATION NAME (VERY IMPORTANT)
spring.application.name=API-GATEWAY

# SERVER PORT (Gateway Port)

server.port=8085


# EUREKA CLIENT CONFIG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ENABLE DISCOVERY-BASED ROUTING


spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true